syntax on
noremap <F5> <Esc>:syntax sync fromstart<CR>
inoremap <F5> <C-o>:syntax sync fromstart<CR>
set nohidden
set autochdir

" Tab settings
set autoindent
set smarttab
set shiftwidth=4
set tabstop=4

" Show trailing whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter * match ExtraWhitespace /\s\+$\| \+\ze\t/
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhitespace /\s\+$\| \+\ze\t/

" Smarter search
set ignorecase
set smartcase
set incsearch

""" Bindings

" Splits and tabs
nnoremap <silent> <C-j> <C-W>w
nnoremap <silent> <C-k> <C-W>W
nnoremap <silent> <C-l> :tabnext<CR>
nnoremap <silent> <C-h> :tabprevious<CR>
nnoremap <silent> <C-c> :Texplore<CR>
nnoremap <silent> <C-z> :split<CR>

" Quickfix shortcuts
nnoremap <silent> ]q :cn<CR>
nnoremap <silent> [q :cp<CR>
